name: Deploy Transaction API

on:
  push:
    branches:
      - main
    paths:
      - api/**

jobs:
  deploy-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: transaction-api-func
          package: api/transaction-api
